[build]
  command = "npm run build"
  publish = "dist/gojs-license-test"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "14.21.3"
  NPM_VERSION = "6.14.18"