[build]
  base = "gojs-license-test"
  command = "npm install && npm run build -- --prod"
  publish = "dist/gojs-license-test"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "14.21.3"
  NPM_VERSION = "6.14.18"