[build]
  base = "gojs-license-test"
  command = "npm ci && npm run build -- --prod"
  publish = "dist/gojs-license-test"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[build.environment]
  NODE_VERSION = "14.21.3"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200