[build]
  command = "cd gojs-license-test && npm ci && npm run build -- --prod"
  publish = "gojs-license-test/dist/gojs-license-test"

[build.environment]
  NODE_VERSION = "14"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200